export const CROCHET_ADD_COLUMNS = 'CROCHET_ADD_COLUMNS';
export const CROCHET_ADD_ROWS = 'CROCHET_ADD_ROWS';
export const CROCHET_APPLY_TOOL = 'CROCHET_APPLY_TOOL';
export const CROCHET_MIRROR_HORIZONTAL = 'CROCHET_MIRROR_HORIZONTAL';
export const CROCHET_MIRROR_VERTICAL = 'CROCHET_MIRROR_VERTICAL';
export const CROCHET_NEW = 'CROCHET_NEW';
export const TOOL_CHOOSE = 'TOOL_CHOOSE';
